######################################################################
# BioSimSpace: Making biomolecular simulation a breeze!
#
# Copyright: 2017-2026
#
# Authors: Lester Hedges <lester.hedges@gmail.com>
#
# BioSimSpace is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# BioSimSpace is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with BioSimSpace. If not, see <http://www.gnu.org/licenses/>.
#####################################################################

"""Functionality for running Hamiltonian replica exchange simulations with AMBER."""

__author__ = "Lester Hedges"
__email__ = "lester.hedges@gmail.com"

__all__ = ["AmberHREX"]


from ._amber import Amber as _Amber


class AmberHREX(_Amber):
    """
    A class for running Hamiltonian replica exchange (HREX) simulations using AMBER.

    Each lambda window runs as a separate MPI rank within a single pmemd.MPI
    invocation using the -rem 3 flag. Exchanges between adjacent lambda
    windows are attempted every repex_frequency steps.

    A shared topology is written once to the process work directory.
    Per-replica coordinate files are written to individual lambda
    subdirectories, and a groupfile is generated for the MPI launch.
    """

    def __init__(
        self,
        system,
        protocol,
        repex_frequency=1000,
        oversubscribe=False,
        explicit_dummies=False,
        exe=None,
        mpi_exe=None,
        is_gpu=False,
        name="amber",
        work_dir=None,
        seed=None,
        extra_options={},
        extra_lines=[],
        property_map={},
    ):
        """
        Constructor.

        Parameters
        ----------

        system : :class:`System <BioSimSpace._SireWrappers.System>` or \
                 :class:`ReplicaSystem <BioSimSpace._SireWrappers.ReplicaSystem>`
            The molecular system. A plain System will be duplicated to create
            one replica per lambda value in the protocol. A ReplicaSystem must
            contain exactly as many replicas as there are lambda values.

        protocol : :class:`Protocol <BioSimSpace.Protocol>`
            The free energy protocol. Must be derived from
            BioSimSpace.Protocol._FreeEnergyMixin.

        repex_frequency : int
            The number of steps between replica exchange attempts. This sets
            ``nstlim`` in each replica's configuration file. The total number
            of exchange cycles is ``protocol.getRunTime() / timestep //
            repex_frequency``. Default is 1000.

        explicit_dummies : bool
            Whether to keep dummy atoms explicit at alchemical end states, or
            remove them. The default is False, which should be used for any
            recent AMBER version or for GPU-accelerated PMEMD.

        oversubscribe : bool
            Whether to pass ``--oversubscribe`` to the MPI launcher, allowing
            more ranks than available CPU slots. Default is False.

        exe : str
            The full path to the AMBER MPI executable (e.g. pmemd.MPI). When
            None, the executable found via AMBERHOME or PATH is used.

        mpi_exe : str
            The full path to the MPI launcher (e.g. mpirun, mpiexec, srun).
            When None, ``mpirun`` is located on PATH.

        is_gpu : bool
            Whether to use the GPU-accelerated MPI version of AMBER
            (pmemd.cuda.MPI). Default is False.

        name : str
            The name of the process.

        work_dir :
            The working directory for the process.

        seed : int
            A random number seed.

        extra_options : dict
            A dictionary containing extra options. Overrides the defaults
            generated by the protocol. Applied to every replica's configuration
            file.

        extra_lines : [str]
            A list of extra lines to put at the end of each configuration file.

        property_map : dict
            A dictionary that maps system "properties" to their user defined
            values. This allows the user to refer to properties with their
            own naming scheme, e.g. { "charge" : "my-charge" }
        """

        from .._SireWrappers import ReplicaSystem as _ReplicaSystem
        from .._SireWrappers import System as _System
        from ..Protocol._free_energy_mixin import _FreeEnergyMixin

        # Protocol must be a free energy protocol.
        if not isinstance(protocol, _FreeEnergyMixin):
            raise TypeError(
                "'protocol' must be a free energy protocol derived from "
                "'BioSimSpace.Protocol._FreeEnergyMixin'."
            )

        # Only the "full" perturbation type is supported.
        if protocol.getPerturbationType() != "full":
            raise NotImplementedError(
                "'BioSimSpace.Process.AmberHREX' currently only supports the "
                "'full' perturbation type. Please use 'BioSimSpace.Process.Somd' "
                "for multistep perturbation types."
            )

        if not isinstance(repex_frequency, int) or repex_frequency < 1:
            raise ValueError("'repex_frequency' must be a positive integer.")

        if not isinstance(is_gpu, bool):
            raise TypeError("'is_gpu' must be of type 'bool'.")

        if not isinstance(oversubscribe, bool):
            raise TypeError("'oversubscribe' must be of type 'bool'.")

        # Get the lambda values from the protocol.
        lam_vals = protocol.getLambdaValues()
        n_replicas = len(lam_vals)

        # Validate and promote the system.
        if isinstance(system, _ReplicaSystem):
            if system.nReplicas() != n_replicas:
                raise ValueError(
                    f"The number of replicas in 'system' ({system.nReplicas()}) "
                    f"does not match the number of lambda values ({n_replicas})."
                )
            self._replica_system = system
            # Extract the first replica for the base class constructor.
            system_for_base = system.getReplica(0)
        elif isinstance(system, _System):
            self._replica_system = _ReplicaSystem(system, num_replicas=n_replicas)
            system_for_base = system
        else:
            raise TypeError(
                "'system' must be of type 'BioSimSpace._SireWrappers.System' "
                "or 'BioSimSpace._SireWrappers.ReplicaSystem'."
            )

        # Store HREX-specific attributes before calling super().__init__(),
        # because the parent constructor calls self._setup(), which needs these.
        self._repex_frequency = repex_frequency
        self._oversubscribe = oversubscribe
        self._mpi_exe = mpi_exe
        self._lam_vals = lam_vals
        self._n_replicas = n_replicas

        # Initialise attributes that will be populated by _setup().
        self._lambda_dirs = None
        self._rst_out_files = None
        self._squashed_systems = None
        self._hrex_mapping = None

        # Resolve the MPI executable before calling the parent constructor.
        if exe is None:
            exe = _findHrexExe(is_gpu=is_gpu)

        # Call the parent constructor using the single-replica system.
        super().__init__(
            system_for_base,
            protocol,
            explicit_dummies=explicit_dummies,
            exe=exe,
            name=name,
            work_dir=work_dir,
            seed=seed,
            extra_options=extra_options,
            extra_lines=extra_lines,
            property_map=property_map,
        )

    def _setup(self):
        """Setup input files and per-lambda working directories."""
        import os as _os

        from .. import IO as _IO
        from .. import Protocol as _Protocol
        from .. import _isVerbose
        from ..Align._squash import _squash

        # Check that the system contains a perturbable molecule.
        if self._system.nPerturbableMolecules() == 0:
            raise ValueError(
                "'BioSimSpace.Protocol.FreeEnergy' requires a perturbable molecule!"
            )

        # Compute the total number of simulation steps and exchange cycles.
        total_steps = self._protocol.getRunTime() / self._protocol.getTimeStep()
        total_steps = int(round(float(total_steps)))
        num_exchanges = max(1, total_steps // self._repex_frequency)

        # Build per-lambda directory paths and create the directories.
        lambda_dirs = []
        for lam in self._lam_vals:
            lam_dir = _os.path.join(str(self._work_dir), f"lambda_{lam:5.4f}")
            _os.makedirs(lam_dir, exist_ok=True)
            lambda_dirs.append(_os.path.abspath(lam_dir))
        self._lambda_dirs = lambda_dirs

        # Squash each replica to remove dummy atoms and collect the results.
        squashed_systems = []
        hrex_mapping = None

        for i in range(self._n_replicas):
            replica = self._replica_system.getReplica(i)
            replica._set_water_topology("AMBER", property_map=self._property_map)

            sq, m = _squash(replica, explicit_dummies=self._explicit_dummies)
            squashed_systems.append(sq)
            # All replicas share the same topology and atom mapping.
            if hrex_mapping is None:
                hrex_mapping = m

        self._squashed_systems = squashed_systems
        self._hrex_mapping = hrex_mapping

        # Write the shared topology from the first squashed replica.
        try:
            top_base = _os.path.splitext(self._top_file)[0]
            _IO.saveMolecules(
                top_base,
                squashed_systems[0],
                "prm7",
                match_water=False,
                property_map=self._property_map,
            )
        except Exception as e:
            msg = "Failed to write system to 'PRM7' format."
            if _isVerbose():
                raise IOError(msg) from e
            else:
                raise IOError(msg) from None

        # Write the shared reference file (copy the first squashed replica).
        try:
            ref_base = _os.path.splitext(self._ref_file)[0]
            _IO.saveMolecules(
                ref_base,
                squashed_systems[0],
                "rst7",
                property_map=self._property_map,
            )
        except Exception as e:
            msg = "Failed to write reference system to 'RST7' format."
            if _isVerbose():
                raise IOError(msg) from e
            else:
                raise IOError(msg) from None

        # Write per-lambda RST7 and CFG files.
        rst_files = []
        cfg_files = []
        rst_out_files = []
        input_files = [self._top_file, self._ref_file]

        for i, (lam, lam_dir, sq) in enumerate(
            zip(self._lam_vals, self._lambda_dirs, squashed_systems)
        ):
            rst_file = _os.path.join(lam_dir, f"{self._name}.rst7")
            cfg_file = _os.path.join(lam_dir, f"{self._name}.cfg")
            rst_out = _os.path.join(lam_dir, f"{self._name}.crd")

            # Write the per-replica input coordinates.
            try:
                rst_base = _os.path.splitext(rst_file)[0]
                _IO.saveMolecules(rst_base, sq, "rst7", property_map=self._property_map)
            except Exception as e:
                msg = f"Failed to write RST7 for lambda={lam}."
                if _isVerbose():
                    raise IOError(msg) from e
                else:
                    raise IOError(msg) from None

            # Temporarily set the protocol lambda to this window so that
            # ConfigFactory writes the correct clambda.
            self._protocol.setLambdaValues(lam=lam, lam_vals=self._lam_vals)

            # Build extra options for HREX: override nstlim and add numexchg.
            hrex_options = dict(self._extra_options) if self._extra_options else {}
            if self._seed is None:
                hrex_options.setdefault("ig", -1)
            else:
                hrex_options.setdefault("ig", self._seed)
            hrex_options["nstlim"] = self._repex_frequency
            hrex_options["numexchg"] = num_exchanges

            # Generate the AMBER configuration for this lambda window.
            config = _Protocol.ConfigFactory(
                squashed_systems[0], self._protocol, self._explicit_dummies
            )
            config_lines = config.generateAmberConfig(
                extra_options=hrex_options,
                extra_lines=self._extra_lines,
            )

            # Write the CFG file.
            with open(cfg_file, "w") as f:
                for line in config_lines:
                    f.write(f"{line}\n")

            rst_files.append(rst_file)
            cfg_files.append(cfg_file)
            rst_out_files.append(rst_out)
            input_files += [rst_file, cfg_file]

        self._rst_out_files = rst_out_files

        # Write the groupfile. Each line provides the arguments for one MPI rank.
        # Paths are relative to the work directory since pmemd.MPI runs there.
        groupfile = _os.path.join(str(self._work_dir), "groupfile")
        with open(groupfile, "w") as f:
            for lam in self._lam_vals:
                lam_name = f"lambda_{lam:5.4f}"
                line = (
                    f"-O "
                    f"-i {lam_name}/{self._name}.cfg "
                    f"-p {self._name}.prm7 "
                    f"-c {lam_name}/{self._name}.rst7 "
                    f"-o {lam_name}/{self._name}.out "
                    f"-r {lam_name}/{self._name}.crd "
                    f"-x {lam_name}/{self._name}.nc "
                    f"-inf {lam_name}/{self._name}.nrg"
                )
                f.write(f"{line}\n")
        input_files.append(groupfile)

        self._groupfile = groupfile
        self._input_files = input_files

        # Clear the args dict; start() constructs the full mpirun command directly.
        self.clearArgs()

        return self._input_files

    def _generate_args(self):
        """
        Generate the dictionary of command-line arguments.

        For AmberHREX the full mpirun command is assembled in start(), so
        this method only clears any existing arguments.
        """
        self.clearArgs()

    def start(self):
        """
        Start the AMBER HREX process.

        Returns
        -------

        process : :class:`Process.AmberHREX <BioSimSpace.Process.AmberHREX>`
            A handle to the AMBER HREX process.
        """
        import shutil as _shutil
        import timeit as _timeit

        from sire.legacy import Base as _SireBase

        from .. import _Utils
        from .._Exceptions import MissingSoftwareError as _MissingSoftwareError

        # The process is currently queued.
        if self.isQueued():
            return

        # Process is already running.
        if self._process is not None:
            if self._process.is_running():
                return

        # Clear any existing output.
        self._clear_output()

        with _Utils.cd(self._work_dir):
            # Locate the MPI launcher.
            mpirun = self._mpi_exe or _shutil.which("mpirun")
            if mpirun is None:
                raise _MissingSoftwareError(
                    "Cannot find 'mpirun' on PATH. AmberHREX requires native "
                    "MPI. Ensure an MPI implementation is installed and "
                    "available, or set mpi_exe explicitly."
                )

            # Build argument list:
            # mpirun [--oversubscribe] -np N pmemd.MPI -rem 3 -ng N -groupfile groupfile
            args = []
            if self._oversubscribe:
                args.append("--oversubscribe")
            args += [
                "-np",
                str(self._n_replicas),
                self._exe,
                "-rem",
                "3",
                "-ng",
                str(self._n_replicas),
                "-groupfile",
                "groupfile",
            ]

            # Write the command to README.txt for reproducibility.
            with open("README.txt", "w") as f:
                self._command = mpirun + " " + " ".join(str(a) for a in args)
                f.write("# AMBER HREX was run with the following command:\n")
                f.write(f"{self._command}\n")

            # Start the timer.
            self._timer = _timeit.default_timer()

            # Launch the process.
            self._process = _SireBase.Process.run(
                mpirun,
                args,
                "",
                f"{self._name}.err",
            )

        return self

    def getSystem(self, block="AUTO"):
        """
        Get the latest molecular system.

        Parameters
        ----------

        block : bool
            Whether to block until the process has finished running.

        Returns
        -------

        system : :class:`ReplicaSystem <BioSimSpace._SireWrappers.ReplicaSystem>`
            The latest replica system, with one coordinate set per lambda
            window. Returns None if no output coordinates are available yet.
        """
        import os as _os
        import shutil as _shutil
        import tempfile as _tempfile
        import warnings as _warnings

        from sire.legacy import IO as _SireIO
        from sire.legacy import Mol as _SireMol

        from .. import IO as _IO
        from .._SireWrappers import ReplicaSystem as _ReplicaSystem
        from .._SireWrappers import System as _System
        from ..Align._squash import _unsquash

        # Wait for the process to finish.
        if block is True:
            self.wait()
        elif block == "AUTO" and self._is_blocked:
            self.wait()

        # Warn the user if the process has exited with an error.
        if self.isError():
            _warnings.warn("The process exited with an error!")

        # Collect available output coordinate files.
        available_indices = [
            i for i, f in enumerate(self._rst_out_files) if _os.path.isfile(f)
        ]

        if not available_indices:
            return None

        if len(available_indices) < self._n_replicas:
            _warnings.warn(
                f"Only {len(available_indices)} of {self._n_replicas} output "
                "coordinate files are currently available."
            )

        # Determine whether to use lambda=1 coordinates.
        is_lambda1 = "is_lambda1" in self._property_map

        # Unsquash each available replica and collect unsquashed systems.
        unsquashed_systems = []
        for i in available_indices:
            rst_out = self._rst_out_files[i]
            sq = self._squashed_systems[i]
            old_system = self._replica_system.getReplica(i)

            # Copy the restart file to avoid Sire's stream caching.
            with _tempfile.TemporaryDirectory() as tmp_dir:
                tmp_file = f"{tmp_dir}/{self._name}.crd"
                _shutil.copyfile(rst_out, tmp_file)

                new_system = _System(
                    _SireIO.MoleculeParser.read(
                        [tmp_file, self._top_file], self._property_map
                    )
                )

            # Update the squashed system's coordinates from the restart file.
            sq_mapping = {
                _SireMol.MolIdx(x): _SireMol.MolIdx(x) for x in range(sq.nMolecules())
            }
            sq_updated = sq.copy()
            (
                sq_updated._sire_object,
                _,
            ) = _SireIO.updateCoordinatesAndVelocities(
                sq_updated._sire_object,
                new_system._sire_object,
                sq_mapping,
                is_lambda1,
                self._property_map,
                self._property_map,
            )

            # Unsquash to recover the full system with dummy atoms.
            updated = _unsquash(
                old_system,
                sq_updated,
                self._hrex_mapping,
                explicit_dummies=self._explicit_dummies,
            )

            # Propagate box information if present.
            if "space" in new_system._sire_object.property_keys():
                box = new_system._sire_object.property("space")
                if box.is_periodic():
                    updated._sire_object.set_property(
                        self._property_map.get("space", "space"), box
                    )

            unsquashed_systems.append(updated)

        # Save each unsquashed system to a temporary RST7 file, then load all
        # of them together via ReplicaSystem.loadReplicas to build the result.
        with _tempfile.TemporaryDirectory() as tmp_dir:
            tmp_rst7_files = []
            for j, sys in enumerate(unsquashed_systems):
                tmp_base = _os.path.join(tmp_dir, f"replica_{j}")
                _IO.saveMolecules(
                    tmp_base, sys, "rst7", property_map=self._property_map
                )
                tmp_rst7_files.append(f"{tmp_base}.rst7")

            return _ReplicaSystem.loadReplicas(self._replica_system, tmp_rst7_files)

    def getCurrentSystem(self):
        """
        Get the latest molecular system.

        Returns
        -------

        system : :class:`ReplicaSystem <BioSimSpace._SireWrappers.ReplicaSystem>`
            The latest replica system.
        """
        return self.getSystem(block=False)

    def getExchangeStatistics(self):
        """
        Get replica exchange acceptance statistics.

        Parses the AMBER ``remlog`` file that is written alongside the
        replica exchange simulation.

        Returns
        -------

        statistics : pandas.DataFrame or None
            A DataFrame with columns ``replica_i``, ``replica_j``,
            ``lambda_i``, ``lambda_j``, ``n_attempts``, ``n_accepted``, and
            ``acceptance_rate``. Returns None if no exchange statistics are
            available yet.
        """
        import os as _os
        import re as _re
        from collections import defaultdict as _defaultdict

        import pandas as _pd

        remlog = _os.path.join(str(self._work_dir), "remlog")

        if not _os.path.isfile(remlog):
            return None

        with open(remlog) as f:
            content = f.read()

        attempt_pattern = _re.compile(
            r"exchange:\s+(\d+)\s+\([\d.]+\)\s+<->\s+(\d+)\s+\([\d.]+\)\s*:\s*(\w+)",
            _re.IGNORECASE,
        )

        counts = _defaultdict(lambda: {"attempts": 0, "accepted": 0})
        for m in attempt_pattern.finditer(content):
            i = int(m.group(1))
            j = int(m.group(2))
            outcome = m.group(3).lower()
            key = (min(i, j), max(i, j))
            counts[key]["attempts"] += 1
            if outcome == "success":
                counts[key]["accepted"] += 1

        if not counts:
            return None

        rows = []
        for (i, j), c in sorted(counts.items()):
            n_attempts = c["attempts"]
            n_accepted = c["accepted"]
            rows.append(
                {
                    "replica_i": i,
                    "replica_j": j,
                    "lambda_i": (
                        self._lam_vals[i] if i < len(self._lam_vals) else None
                    ),
                    "lambda_j": (
                        self._lam_vals[j] if j < len(self._lam_vals) else None
                    ),
                    "n_attempts": n_attempts,
                    "n_accepted": n_accepted,
                    "acceptance_rate": (
                        n_accepted / n_attempts if n_attempts > 0 else 0.0
                    ),
                }
            )

        return _pd.DataFrame(rows)


def _findHrexExe(is_gpu=False):
    """
    Helper function to search for an AMBER MPI executable for HREX.

    Parameters
    ----------

    is_gpu : bool
        Whether to search for a GPU-enabled MPI executable.

    Returns
    -------

    exe : str
        The path to the executable.
    """
    import os as _os
    import pathlib as _pathlib
    from glob import glob as _glob

    from .. import _amber_home
    from .._Exceptions import MissingSoftwareError as _MissingSoftwareError

    if is_gpu:
        targets = ["pmemd.cuda.MPI"]
    else:
        targets = ["pmemd.MPI"]

    # Get the current path, prepending AMBERHOME/bin if set.
    path = _os.environ["PATH"].split(_os.pathsep)
    if _amber_home is not None:
        path = [_amber_home + "/bin"] + path

    def is_exe(fpath):
        return _os.path.isfile(fpath) and _os.access(fpath, _os.X_OK)

    for p in path:
        for t in targets:
            results = _glob(f"{t}*", root_dir=p)
            for exe in results:
                if "LES" not in exe:
                    exe = _pathlib.Path(p) / exe
                    if is_exe(exe):
                        return str(exe)

    target_str = "pmemd.cuda.MPI" if is_gpu else "pmemd.MPI"
    raise _MissingSoftwareError(
        f"'BioSimSpace.Process.AmberHREX' is not supported. "
        f"Unable to find '{target_str}' in AMBERHOME or PATH. "
        "Please ensure AMBER was compiled with MPI support "
        "(http://ambermd.org)."
    )
