######################################################################
# BioSimSpace: Making biomolecular simulation a breeze!
#
# Copyright: 2017-2026
#
# Authors: Lester Hedges <lester.hedges@gmail.com>
#
# BioSimSpace is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# BioSimSpace is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with BioSimSpace. If not, see <http://www.gnu.org/licenses/>.
#####################################################################

"""Functionality for running Hamiltonian replica exchange simulations with GROMACS."""

__author__ = "Lester Hedges"
__email__ = "lester.hedges@gmail.com"

__all__ = ["GromacsHREX"]


from ._gromacs import Gromacs as _Gromacs


class GromacsHREX(_Gromacs):
    """
    A class for running Hamiltonian replica exchange (HREX) simulations using GROMACS.

    Each lambda window runs as a separate rank within a single gmx mdrun
    invocation using the -multidir flag. Exchanges between adjacent lambda
    windows are attempted every repex_frequency steps.

    A shared topology is written once to the process work directory.
    Per-replica coordinate files are written efficiently via
    ReplicaSystem.saveReplicas, avoiding redundant topology writes.
    """

    def __init__(
        self,
        system,
        protocol,
        repex_frequency=1000,
        oversubscribe=False,
        exe=None,
        mpi_exe=None,
        name="gromacs",
        work_dir=None,
        seed=None,
        extra_options={},
        extra_lines=[],
        property_map={},
        restraint=None,
        ignore_warnings=False,
        show_errors=True,
    ):
        """
        Constructor.

        Parameters
        ----------

        system : :class:`System <BioSimSpace._SireWrappers.System>` or \
                 :class:`ReplicaSystem <BioSimSpace._SireWrappers.ReplicaSystem>`
            The molecular system. A plain System will be duplicated to create
            one replica per lambda value in the protocol. A ReplicaSystem must
            contain exactly as many replicas as there are lambda values.

        protocol : :class:`Protocol <BioSimSpace.Protocol>`
            The free energy protocol. Must be derived from
            BioSimSpace.Protocol._FreeEnergyMixin.

        repex_frequency : int
            The number of steps between replica exchange attempts. Passed as
            ``-replex`` to gmx mdrun. Default is 1000.

        oversubscribe : bool
            Whether to pass ``--oversubscribe`` to mpirun, allowing more MPI
            ranks than available CPU slots. Useful when each rank runs on a GPU
            and the number of lambda windows exceeds the CPU core count.
            Default is False.

        exe : str
            The full path to the MPI-enabled GROMACS executable (e.g. gmx_mpi).
            When None, the executable found at BioSimSpace initialisation is used.

        mpi_exe : str
            The full path to the MPI launcher (e.g. mpirun, mpiexec, srun).
            When None, ``mpirun`` is located on PATH.

        name : str
            The name of the process.

        work_dir :
            The working directory for the process.

        seed : int
            A random number seed.

        extra_options : dict
            A dictionary containing extra options. Overrides the defaults
            generated by the protocol.

        extra_lines : [str]
            A list of extra lines to put at the end of each MDP configuration
            file.

        property_map : dict
            A dictionary that maps system "properties" to their user defined
            values. This allows the user to refer to properties with their
            own naming scheme, e.g. { "charge" : "my-charge" }

        restraint : :class:`Restraint <BioSimSpace.FreeEnergy.Restraint>` or None
            An optional ABFE restraint object for ``release_restraint``
            perturbation types.

        ignore_warnings : bool
            Whether to ignore warnings when generating binary run files with
            ``gmx grompp``. By default these warnings are elevated to errors
            and will halt the program.

        show_errors : bool
            Whether to show warning/error messages when generating binary run
            files.
        """

        from .._SireWrappers import ReplicaSystem as _ReplicaSystem
        from .._SireWrappers import System as _System
        from ..Protocol._free_energy_mixin import _FreeEnergyMixin

        # Protocol must be a free energy protocol.
        if not isinstance(protocol, _FreeEnergyMixin):
            raise TypeError(
                "'protocol' must be a free energy protocol derived from "
                "'BioSimSpace.Protocol._FreeEnergyMixin'."
            )

        # Only "full" and "release_restraint" perturbation types are supported.
        pert_type = protocol.getPerturbationType()
        if pert_type not in ("full", "release_restraint"):
            raise NotImplementedError(
                "'BioSimSpace.Process.GromacsHREX' currently only supports the "
                "'full' and 'release_restraint' perturbation types. Please use "
                "'BioSimSpace.Process.Somd' for other multistep perturbation types."
            )

        if pert_type == "release_restraint":
            if restraint is None:
                raise ValueError(
                    "'BioSimSpace.Process.GromacsHREX' requires a restraint for "
                    "the 'release_restraint' perturbation type."
                )
            from ..FreeEnergy._restraint import Restraint as _Restraint

            if not isinstance(restraint, _Restraint):
                raise TypeError(
                    "'restraint' must be of type 'BioSimSpace.FreeEnergy.Restraint'."
                )
            if restraint._restraint_type != "multiple_distance":
                raise ValueError(
                    "The 'release_restraint' perturbation type requires a "
                    "multiple distance restraint."
                )

        if not isinstance(repex_frequency, int) or repex_frequency < 1:
            raise ValueError("'repex_frequency' must be a positive integer.")

        if not isinstance(oversubscribe, bool):
            raise TypeError("'oversubscribe' must be of type 'bool'.")

        # Get the lambda values from the protocol.
        lam_vals = protocol.getLambdaValues()
        n_replicas = len(lam_vals)

        # Validate and promote the system.
        if isinstance(system, _ReplicaSystem):
            if system.nReplicas() != n_replicas:
                raise ValueError(
                    f"The number of replicas in 'system' ({system.nReplicas()}) "
                    f"does not match the number of lambda values ({n_replicas})."
                )
            self._replica_system = system
            # Extract the first replica for the base class constructor.
            system_for_base = system.getReplica(0)
        elif isinstance(system, _System):
            self._replica_system = _ReplicaSystem(system, num_replicas=n_replicas)
            system_for_base = system
        else:
            raise TypeError(
                "'system' must be of type 'BioSimSpace._SireWrappers.System' "
                "or 'BioSimSpace._SireWrappers.ReplicaSystem'."
            )

        # Store REMD-specific attributes before calling super().__init__(),
        # because the parent constructor calls self._setup(), which needs these.
        self._repex_frequency = repex_frequency
        self._oversubscribe = oversubscribe
        self._mpi_exe = mpi_exe
        self._lam_vals = lam_vals
        self._n_replicas = n_replicas

        # Initialise attributes that will be populated by _setup().
        self._lambda_dirs = None
        self._gro_out_files = None
        self._tpr_files = None

        # Call the parent constructor using the single-replica system.
        super().__init__(
            system_for_base,
            protocol,
            exe=exe,
            name=name,
            work_dir=work_dir,
            seed=seed,
            extra_options=extra_options,
            extra_lines=extra_lines,
            property_map=property_map,
            restraint=restraint,
            ignore_warnings=ignore_warnings,
            show_errors=show_errors,
        )

    def _setup(self):
        """Setup input files and per-lambda working directories."""
        import os as _os
        import shutil as _shutil

        import sire.vol as _SireVol
        import sire.maths as _SireMaths

        from .. import IO as _IO
        from .. import Protocol as _Protocol

        # Create a copy of the system with the GROMACS water topology applied.
        system = self._system.copy()
        system._set_water_topology("GROMACS", property_map=self._property_map)

        # Check whether the system has a periodic box. If not, apply a large
        # pseudo-periodic box (999.9 nm) so that grompp accepts the GRO file
        # for vacuum / non-periodic simulations (pbc=xyz, large cut-offs).
        space_prop = self._property_map.get("space", "space")
        has_box = False
        if space_prop in system._sire_object.property_keys():
            try:
                box = system._sire_object.property(space_prop)
                has_box = box.is_periodic()
            except Exception:
                pass
        if not has_box or not self._has_water:
            space = _SireVol.PeriodicBox(_SireMaths.Vector(9999, 9999, 9999))
            system._sire_object.set_property(space_prop, space)

        # Check that the system contains a perturbable molecule.
        if (
            self._system.nPerturbableMolecules() == 0
            and self._system.nDecoupledMolecules() == 0
        ):
            raise ValueError(
                "'BioSimSpace.Protocol.FreeEnergy' requires a perturbable molecule!"
            )

        # Write the shared topology once to the top-level work directory.
        top_base = _os.path.splitext(self._top_file)[0]
        _IO.saveMolecules(
            top_base,
            system,
            "grotop",
            match_water=False,
            property_map=self._property_map,
        )

        # Apply ABFE restraint to the shared topology if needed.
        self._apply_ABFE_restraint()

        # Write reference coordinates (copy of the first GRO; no restraint support).
        ref_base = _os.path.splitext(self._ref_file)[0]
        _IO.saveMolecules(
            ref_base,
            system,
            "gro87",
            match_water=False,
            property_map=self._property_map,
        )

        # Build config_options for position restraints.
        config_options = {}
        if isinstance(self._protocol, _Protocol._PositionRestraintMixin):
            self._add_position_restraints(config_options)

        # Build per-lambda GRO file paths.
        # _lam_vals is a list of floats (RBFE) or a DataFrame (multi-column ABFE).
        # For DataFrame, use the row index as the directory name.
        import pandas as _pd

        _lam_is_df = isinstance(self._lam_vals, _pd.DataFrame)
        if _lam_is_df:
            _lam_indices = list(self._lam_vals.index)
        else:
            _lam_indices = [f"{lam:5.4f}" for lam in self._lam_vals]

        gro_files = [
            _os.path.join(str(self._work_dir), f"lambda_{idx}", "gromacs.gro")
            for idx in _lam_indices
        ]

        # Create the per-lambda subdirectories.
        for gro in gro_files:
            _os.makedirs(_os.path.dirname(gro), exist_ok=True)

        # All replicas start from the same coordinates. Write one GRO and copy.
        gro_base = _os.path.splitext(gro_files[0])[0]
        _IO.saveMolecules(
            gro_base,
            system,
            "gro87",
            match_water=False,
            property_map=self._property_map,
        )
        for gro in gro_files[1:]:
            _shutil.copy(gro_files[0], gro)

        # Generate per-lambda MDP and TPR files.
        tpr_files = []
        _lam_iter = (
            ((idx, row) for idx, row in self._lam_vals.iterrows())
            if _lam_is_df
            else ((idx, lam) for idx, lam in zip(_lam_indices, self._lam_vals))
        )
        for (lam_idx, lam), gro in zip(_lam_iter, gro_files):
            lam_dir = _os.path.dirname(gro)
            mdp_file = _os.path.join(lam_dir, "gromacs.mdp")
            tpr_file = _os.path.join(lam_dir, "gromacs.tpr")

            # Update the protocol lambda so that ConfigFactory writes the
            # correct init-lambda-state for this window.
            self._protocol.setLambdaValues(lam=lam, lam_vals=self._lam_vals)

            # Generate MDP configuration strings for this lambda window.
            pert_type = (
                self._protocol._perturbation_type
                if isinstance(self._protocol, _Protocol._FreeEnergyMixin)
                else None
            )
            config = _Protocol.ConfigFactory(system, self._protocol)
            config_lines = config.generateGromacsConfig(
                extra_options={**config_options, **self._extra_options},
                extra_lines=self._extra_lines,
                restraint=self._restraint,
                perturbation_type=pert_type,
            )

            # Write the MDP file.
            with open(mdp_file, "w") as f:
                for line in config_lines:
                    f.write(f"{line}\n")

            # Generate the binary run file.
            self._generate_binary_run_file(
                mdp_file,
                gro,
                self._top_file,
                self._ref_file,
                tpr_file,
                self._exe,
                ignore_warnings=self._ignore_warnings,
                show_errors=self._show_errors,
            )

            tpr_files.append(tpr_file)

        # Store per-lambda paths using absolute paths.
        self._lambda_dirs = [
            _os.path.abspath(_os.path.dirname(gro)) for gro in gro_files
        ]
        self._gro_out_files = [
            _os.path.join(d, f"{self._name}_out.gro") for d in self._lambda_dirs
        ]
        self._tpr_files = tpr_files

        # Update the input file list.
        self._input_files = [self._top_file, self._ref_file] + gro_files + tpr_files

        # Clear the args dict; start() constructs the full mdrun command directly.
        self._generate_args()

        return self._input_files

    def _generate_args(self):
        """
        Generate the dictionary of command-line arguments.

        For GromacsHREX the full mdrun command is assembled in start(), so
        this method only clears any existing arguments.
        """
        self.clearArgs()

    def start(self):
        """
        Start the GROMACS HREX process.

        Returns
        -------

        process : :class:`Process.GromacsHREX <BioSimSpace.Process.GromacsHREX>`
            A handle to the GROMACS HREX process.
        """
        import shutil as _shutil
        import timeit as _timeit

        from sire.legacy import Base as _SireBase

        from .. import _Utils
        from .._Exceptions import MissingSoftwareError as _MissingSoftwareError

        # The process is currently queued.
        if self.isQueued():
            return

        # Process is already running.
        if self._process is not None:
            if self._process.is_running():
                return

        # Clear any existing output.
        self._clear_output()

        with _Utils.cd(self._work_dir):
            # GROMACS -multidir requires an MPI-enabled build; launch via mpirun.
            mpirun = self._mpi_exe or _shutil.which("mpirun")
            if mpirun is None:
                raise _MissingSoftwareError(
                    "Cannot find 'mpirun' on PATH. An MPI-enabled GROMACS "
                    "build (gmx_mpi) is required for HREX -multidir runs, "
                    "or set mpi_exe explicitly."
                )
            exe = mpirun
            args = []
            if self._oversubscribe:
                args.append("--oversubscribe")
            args += (
                [
                    "-np",
                    str(self._n_replicas),
                    self._exe,
                    "mdrun",
                    "-deffnm",
                    self._name,
                    "-c",
                    f"{self._name}_out.gro",
                    "-multidir",
                ]
                + self._lambda_dirs
                + ["-replex", str(self._repex_frequency)]
            )

            # Write the command to README.txt for reproducibility.
            with open("README.txt", "w") as f:
                self._command = exe + " " + " ".join(str(a) for a in args)
                f.write("# GROMACS HREX was run with the following command:\n")
                f.write(f"{self._command}\n")

            # Start the timer.
            self._timer = _timeit.default_timer()

            # Launch the process.
            self._process = _SireBase.Process.run(
                exe,
                args,
                f"{self._name}.out",
                f"{self._name}.out",
            )

            # For historical reasons GROMACS writes most output to stderr.
            with open(self._stderr_file, "w") as f:
                f.write("All output has been redirected to the stdout stream!\n")

        return self

    def getSystem(self, block="AUTO"):
        """
        Get the latest molecular system.

        Parameters
        ----------

        block : bool
            Whether to block until the process has finished running.

        Returns
        -------

        system : :class:`ReplicaSystem <BioSimSpace._SireWrappers.ReplicaSystem>`
            The latest replica system, with one coordinate set per lambda
            window. Returns None if no output coordinates are available yet.
        """
        import os as _os
        import warnings as _warnings

        from .._SireWrappers import ReplicaSystem as _ReplicaSystem

        # Wait for the process to finish.
        if block is True:
            self.wait()
        elif block == "AUTO" and self._is_blocked:
            self.wait()

        # Warn the user if the process has exited with an error.
        if self.isError():
            _warnings.warn("The process exited with an error!")

        # Collect output coordinate files that are available so far.
        existing = [f for f in self._gro_out_files if _os.path.isfile(f)]

        if not existing:
            return None

        if len(existing) < self._n_replicas:
            _warnings.warn(
                f"Only {len(existing)} of {self._n_replicas} output coordinate "
                "files are currently available."
            )

        return _ReplicaSystem.loadReplicas(self._replica_system, existing)

    def getCurrentSystem(self):
        """
        Get the latest molecular system.

        Returns
        -------

        system : :class:`ReplicaSystem <BioSimSpace._SireWrappers.ReplicaSystem>`
            The latest replica system.
        """
        return self.getSystem(block=False)

    def getExchangeStatistics(self):
        """
        Get replica exchange acceptance statistics.

        Parses the GROMACS log file from the first lambda window, where
        GROMACS writes exchange statistics when using -multidir.

        Returns
        -------

        statistics : pandas.DataFrame or None
            A DataFrame with columns ``replica_i``, ``replica_j``,
            ``lambda_i``, ``lambda_j``, ``n_attempts``, ``n_accepted``, and
            ``acceptance_rate``. Returns None if no exchange statistics are
            available yet.
        """
        import os as _os
        import re as _re

        import pandas as _pd

        # Exchange statistics are written to the log of the first replica.
        log_file = _os.path.join(self._lambda_dirs[0], f"{self._name}.log")

        if not _os.path.isfile(log_file):
            return None

        with open(log_file) as f:
            content = f.read()

        pattern = _re.compile(
            r"Repl\s+(\d+)\s+<->\s+(\d+)\s*:.*?(\d+)\s+(?:out\s+of|of)\s+(\d+)",
            _re.IGNORECASE,
        )

        rows = []
        for m in pattern.finditer(content):
            i = int(m.group(1))
            j = int(m.group(2))
            n_accepted = int(m.group(3))
            n_attempts = int(m.group(4))
            rows.append(
                {
                    "replica_i": i,
                    "replica_j": j,
                    "lambda_i": self._lam_vals[i],
                    "lambda_j": self._lam_vals[j],
                    "n_attempts": n_attempts,
                    "n_accepted": n_accepted,
                    "acceptance_rate": (
                        n_accepted / n_attempts if n_attempts > 0 else 0.0
                    ),
                }
            )

        if not rows:
            return None

        return _pd.DataFrame(rows)
