import pytest

import BioSimSpace as BSS
from tests.conftest import has_amber, url


@pytest.mark.skipif(has_amber is False, reason="Requires AMBER to be installed.")
def test_makeCompatibleWith():
    # Load the original PDB file. In this representation the system contains
    # a single molecule with two chains. We parse with pdb4amber to ensure
    # that the file can be parsed with tLEaP.
    system = BSS.IO.readPDB(f"{url}/1jr5.pdb", pdb4amber=True)

    # Parameterise with ff14SB and return the molecule. The system that is
    # generated by tLEaP contains two molecules, each corresponding to one
    # of the chains in the original system. The properties from the new system
    # are mapped back into the existing single-molecule format to preserve
    # chain information.
    molecule = BSS.Parameters.ff14SB(system[0]).getMolecule()

    # Load in the two-molecule tLEaP system.
    tLEaP_system = BSS.IO.readMolecules([f"{url}/1jr5.crd", f"{url}/1jr5.top"])

    # Now perform single-point energy calculations using the two molecular
    # representations.

    # Create a single-step minimisation protocol.
    protocol = BSS.Protocol.Minimisation(steps=1)

    # Create a process for the single molecule representation.
    process0 = BSS.Process.Amber(molecule.toSystem(), protocol)

    # Create a process for the multi molecule representation.
    process1 = BSS.Process.Amber(tLEaP_system, protocol)

    # Run the processes and wait for them to finish.
    process0.start()
    process0.wait()
    process1.start()
    process1.wait()

    # Compare bond energies. (In kJ / mol)
    nrg0 = process0.getBondEnergy().kj_per_mol().value()
    nrg1 = process1.getBondEnergy().kj_per_mol().value()
    assert nrg0 == pytest.approx(nrg1, rel=1e-2)

    # Compare angle energies. (In kJ / mol)
    nrg0 = process0.getAngleEnergy().kj_per_mol().value()
    nrg1 = process1.getAngleEnergy().kj_per_mol().value()
    assert nrg0 == pytest.approx(nrg1, rel=1e-2)

    # Compare dihedral energies. (In kJ / mol)
    nrg0 = process0.getDihedralEnergy().kj_per_mol().value()
    nrg1 = process1.getDihedralEnergy().kj_per_mol().value()
    assert nrg0 == pytest.approx(nrg1, rel=1e-2)

    # Make sure we can load a system from the process for the single-molecule
    # representation. This maps the coordinates back into the original topology.
    new_system = process0.getSystem()


@pytest.mark.parametrize("ignore_waters", [False, True])
def test_hydrogen_mass_repartitioning(system, ignore_waters):
    # Work out the initial mass of the system.
    initial_mass = 0
    for molecule in system:
        for mass in molecule._sire_object.property("mass").to_vector():
            initial_mass += mass.value()

    # Repartition the hydrogen mass.
    system.repartitionHydrogenMass(factor=4)

    # Work out the new mass of the system.
    final_mass = 0
    for molecule in system:
        for mass in molecule._sire_object.property("mass").to_vector():
            final_mass += mass.value()

    # Assert the the masses are approximately the same.
    assert final_mass == pytest.approx(initial_mass)

    # Invert the repartitioning.
    system.repartitionHydrogenMass(factor=1 / 4)

    # Work out the new mass of the system.
    final_mass = 0
    for molecule in system:
        for mass in molecule._sire_object.property("mass").to_vector():
            final_mass += mass.value()

    # Assert the the masses are approximately the same.
    assert final_mass == pytest.approx(initial_mass)


def test_extract(system):
    """Test the extract method."""

    # A list of atom indices to extract.
    idxs = [0, 1, 2, 3]

    # Extract the first molecule from the system.
    mol = system[0]

    # Extract the atoms.
    partial_mol = mol.extract(idxs)

    assert partial_mol.nAtoms() == 4

    # Make sure the numbers match.
    assert partial_mol.number() == mol.number()

    # Extract and renumber.
    partial_mol = mol.extract(idxs, renumber=True)

    # Make sure the numbers are different.
    assert partial_mol.number() != mol.number()


@pytest.mark.skipif(has_amber is False, reason="Requires AMBER to be installed.")
def test_makeCompatibleWith_regression():
    """Test that makeCompatibleWith works correctly for a known regression case."""

    import sire as sr

    # Load the BACE protein.
    protein_xtal = BSS.IO.readMolecules(BSS.IO.expand(url, "bace.pdb"))

    # Remove waters.
    protein = protein_xtal[0].extract(
        [atom.index() for atom in protein_xtal[0].search("not resname WAT").atoms()]
    )

    # Parameterise with ff14SB.
    protein = BSS.Parameters.ff14SB(
        protein, work_dir="debug", ensure_compatible=False
    ).getMolecule()

    # Convert to a Sire System and compute the energy.
    system = sr.system.System(protein.toSystem()._sire_object)
    nrg_compatible = system.energy().value()

    # Load in the tLEaP-generated system and compute the energy.
    system = sr.load("debug/leap.crd", "debug/leap.top")
    nrg_leap = system.energy().value()

    # Make sure the energies are approximately equal.
    assert nrg_compatible == pytest.approx(nrg_leap, rel=1e-5)


def test_translate_custom_coordinates_property(perturbable_system):
    """
    Regresson test to ensure that a molecule with a custom
    coordinates property gets translated correctly.
    """

    from sire.maths import Vector

    # Extract a copy of the perturbable molecule.
    mol = perturbable_system.getPerturbableMolecules()[0].copy()

    # Copy the "coordinates0" property to a custom property installed
    # "test"
    cursor = mol._sire_object.cursor()
    cursor["test"] = cursor["coordinates0"]
    mol._sire_object = cursor.commit()

    # Store the existing coordinates.
    coords0 = mol._sire_object.property("coordinates0").to_vector()
    coords1 = mol._sire_object.property("coordinates1").to_vector()
    coords_test = mol._sire_object.property("test").to_vector()

    # Translate the molecule.
    mol.translate(3 * [BSS.Units.Length.angstrom], property_map={"coordinates": "test"})

    # Get the new coordinates.
    new_coords0 = mol._sire_object.property("coordinates0").to_vector()
    new_coords1 = mol._sire_object.property("coordinates1").to_vector()
    new_coords_test = mol._sire_object.property("test").to_vector()

    # Create a vector of the displacement.
    v_ref = Vector(1.0, 1.0, 1.0)

    # Check that the coordinates have been translated correctly.
    for c_new, c_old in zip(new_coords0, coords0):
        v = c_new - c_old
        assert pytest.approx(v.x().value(), abs=1e-5) == v_ref.x().value()
        assert pytest.approx(v.y().value(), abs=1e-5) == v_ref.y().value()
        assert pytest.approx(v.z().value(), abs=1e-5) == v_ref.z().value()
    for c_new, c_old in zip(new_coords1, coords1):
        v = c_new - c_old
        assert pytest.approx(v.x().value(), abs=1e-5) == v_ref.x().value()
        assert pytest.approx(v.y().value(), abs=1e-5) == v_ref.y().value()
        assert pytest.approx(v.z().value(), abs=1e-5) == v_ref.z().value()
    for c_new, c_old in zip(new_coords_test, coords_test):
        v = c_new - c_old
        assert pytest.approx(v.x().value(), abs=1e-5) == v_ref.x().value()
        assert pytest.approx(v.y().value(), abs=1e-5) == v_ref.y().value()
        assert pytest.approx(v.z().value(), abs=1e-5) == v_ref.z().value()
