"""Compute git version info for rattler-build.

This script computes GIT_DESCRIBE_TAG and GIT_DESCRIBE_NUMBER from the
git history and outputs them in GitHub Actions format for setting
environment variables.

It also writes a _version.py file so that versioneer has a fallback
when .git is not available (e.g., in the tarball used by rattler-build).
"""

import os
import subprocess
import sys

script = os.path.abspath(sys.argv[0])
srcdir = os.path.dirname(os.path.dirname(script))
gitdir = os.path.join(srcdir, ".git")


def run_cmd(cmd):
    p = subprocess.Popen(cmd.split(), stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    stdout, _ = p.communicate()
    return stdout.decode("utf-8").strip()


# Get the full git describe output (e.g., "2024.1.0-5-gabcdef" or "2024.1.0")
describe = run_cmd(f"git --git-dir={gitdir} --work-tree={srcdir} describe --tags")

if "-" in describe:
    # Format: tag-number-hash (e.g., "2024.1.0-5-gabcdef")
    parts = describe.rsplit("-", 2)
    tag = parts[0]
    number = parts[1]
    rev = parts[2]  # e.g., "gabcdef"
    version = f"{tag}+{number}.{rev}"
else:
    # Exactly on a tag
    tag = describe
    number = "0"
    version = tag

print(f"GIT_DESCRIBE_TAG={tag}")
print(f"GIT_DESCRIBE_NUMBER={number}")
print(f"Version={version}")

# Write to GITHUB_ENV if running in GitHub Actions
github_env = os.environ.get("GITHUB_ENV")
if github_env:
    with open(github_env, "a") as f:
        f.write(f"GIT_DESCRIBE_TAG={tag}\n")
        f.write(f"GIT_DESCRIBE_NUMBER={number}\n")
    print("Exported to GITHUB_ENV")

# Write _version.py for versioneer fallback (short form that versioneer uses in sdists)
version_file = os.path.join(srcdir, "python", "BioSimSpace", "_version.py")
with open(version_file, "w") as f:
    f.write(
        f'''# This file was generated by the update_recipe.py script.
version_json = """
{{"version": "{version}", "full-revisionid": null, "dirty": false, "error": null, "date": null}}
"""

def get_versions():
    import json
    return json.loads(version_json)
'''
    )
print(f"Wrote {version_file}")
